version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-api
    ports:
      - 3000:3000
    environment:
      DATABASE_TYPE: postgres
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: test
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: test
    links:
      - db
  db:
    image: postgres:15beta4-alpine3.16
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: test
    volumes:
      - /custom/mount:/var/lib/postgresql/data
